# https://confluence.atlassian.com/x/5Q4SMw
# Only use spaces to indent your .yml configuration.
# -----

image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          - cd src
          - dotnet restore
          - dotnet build
          - dotnet test Tests
